title: abby's site
description: aerospace-grade mechanic building a road to space. rockets, propulsion, and breaking things on purpose.
url: "https://abbyfluoroethane.github.io"
baseurl: ""

markdown: kramdown
permalink: /blog/:title/

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      app_name: "Blog"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"
      app_name: "Projects"
  - scope:
      path: ""
    values:
      layout: "default"
      app_name: "Portfolio"