title: abby's site
description: haiiiii :3
baseurl: ""

# Last.fm Integration
lastfm:
  username: "abby_isnthere"
  api_key: "3d59870650c4a720a39500c654d23eb1"

markdown: kramdown
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
permalink: /blog/:title/

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      app_name: "Blog"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"
      app_name: "Projects"
  - scope:
      path: ""
    values:
      layout: "default"
      app_name: "Portfolio"
